SPMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('app/', permanent=False)),
    path('app/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls.conf import include
from accounts.utils import login_forbidden
from re import template
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.signin, name='login'),
    path('verify/', views.verify, name='verify'),
    path('logout/', views.signout, name='logout'),
    path('register/', views.signup, name='register'),
    path('resend_verification/', views.resend, name='resend'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path(
        'password_change/', 
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change-password.html',
            success_url = reverse_lazy('accounts:password_change_done')
        ), 
        name='password_change'
    ),
    path(
        'password_change/done/', 
        auth_views.PasswordChangeDoneView.as_view(
            template_name='accounts/password-change-done.html',
        ), 
        name='password_change_done'
    ),
    path(
        'password_reset/', 
        login_forbidden(
            auth_views.PasswordResetView.as_view(
                template_name='accounts/password-reset.html',
                html_email_template_name='accounts/password-reset-html-email.html',
                email_template_name= 'accounts/example_message.txt',
                success_url = reverse_lazy('accounts:password_reset_done')
            ),
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/', 
        login_forbidden(
            auth_views.PasswordResetDoneView.as_view(
                template_name='accounts/password-reset-done.html',
            ), 
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/', 
        login_forbidden(
            auth_views.PasswordResetConfirmView.as_view(
                template_name='accounts/password-reset-confirm.html',
                success_url=reverse_lazy('accounts:password_reset_complete')
            ),
        ), 
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        login_forbidden(
            auth_views.PasswordResetCompleteView.as_view(
                template_name='accounts/password-reset-complete.html'
            ), 
        ),
        name='password_reset_complete'
    ),
]

app/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='home'),
    path('stdcwplo', views.studentcoursewiseplo, name='stdcwplo'),
    path('stdpwplo', views.studentprogrmwiseplo, name='stdpwplo'),
    path('stdcourses/', views.getstudentcourses, name='stdcourses'),
    path('plotable', views.PLOacheivementtable, name='plotable'),
    path('facwplo', views.facultycousewisePLO, name='facwplo'),
    path('semcwplo', views.semestercousewisePLO, name='semcwplo'),
    path('plowcour', views.plowisecourseanalysis, name='plowcour'),
    path('semwprogplo', views.semesterwiseploacheivementcntcomp, name='semwprogplo'),
    path('prowplocour', views.programwiseploalnalysisofcourses, name='prowplocour'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):   
    dateOfBirth = models.DateField(null=True)
    gender = models.CharField(max_length=6, null=True)
    phone = models.CharField(max_length=15, null=True)
    email = models.EmailField(unique=True)
    address = models.CharField(max_length=100, null=True)
    is_email_verified = models.BooleanField(default=False)
    
    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.forms import fields

class SignUpForm(UserCreationForm):

    input_field_style = 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input appearance-none bg-transparent'

    username = forms.CharField(
        required=True,
        max_length=150,
        help_text=('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[UnicodeUsernameValidator()],
        error_messages={'unique': ("A user with that username already exists.")},
        widget=forms.TextInput(attrs={'class': input_field_style, 'placeholder': ' '})
    )

    first_name = forms.CharField(
        required=True,
        max_length=12, 
        min_length=4,
        help_text='Required: First Name',
        widget=forms.TextInput(attrs={'class': input_field_style, 'placeholder': ' '})
    )

    last_name = forms.CharField(
        required=True,
        max_length=12, 
        min_length=4, 
        help_text='Required: Last Name',
        widget=forms.TextInput(attrs={'class': input_field_style, 'placeholder': ' '})
    )

    email = forms.EmailField(
        required=True,
        max_length=50, 
        help_text='Required. Inform a valid email address.',
        widget=(forms.TextInput(attrs={'class': input_field_style, 'placeholder': ' '}))
    )

    password1 = forms.CharField(
        required=True,
        widget=(forms.PasswordInput(attrs={'class': input_field_style, 'placeholder': ' '})),
        help_text=password_validation.password_validators_help_text_html()
    )

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': input_field_style, 'placeholder': ' '}),
        help_text=('Just Enter the same password, for confirmation')
    )
    
    '''
    agree_policy = forms.ChoiceField(
        required=True,
        widget=(forms.CheckboxInput(attrs={'class': 'text-purple-600 form-checkbox focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray'}))
    )
    '''
    class Meta:
        model = get_user_model()
        fields = [
            'username', 
            'first_name',
            'last_name',
            'email', 
            'password1', 
            'password2',
        ]

class SignInForm(AuthenticationForm):
    input_field_style = 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input appearance-none bg-transparent'

    username = forms.CharField(
        required=True,
        max_length=50, 
        widget=(forms.TextInput(attrs={'class': input_field_style, 'placeholder': ' ', 'id': 'username'}))
    )

    password = forms.CharField(
        required=True,
        widget=(forms.PasswordInput(attrs={'class': input_field_style, 'placeholder': ' ', 'id': 'password'})),
    )
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

accounts/views.py
from accounts.models import User
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from .forms import SignInForm, SignUpForm
from django.contrib import messages
from .utils import send_activation_email, generate_token
from django.contrib.auth.decorators import login_required

def signup(request):
    if request.user.is_authenticated:
        return redirect('app:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            send_activation_email(request, user)
            return redirect('accounts:verify')
        messages.error(request, "Unsuccessful registration.")
    else:
        form = SignUpForm()

    return render(request, 'accounts/signup.html', {'form': form})

def signin(request):
    if request.user.is_authenticated:
        return redirect('app:home')
    if request.method == 'POST':
        form = SignInForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                if not user.is_email_verified:
                    send_activation_email(request, user)
                    return redirect('accounts:verify')

                return redirect('app:home')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = SignInForm()
    return render(request, 'accounts/signin.html', {'form': form})

@login_required(login_url='accounts:login', redirect_field_name='')
def verify(request):
    if request.user.is_email_verified:
        return redirect('app:home')

    return render(request, 'accounts/verify-email.html')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except Exception as e:
        user = None

    if user and generate_token.check_token(user, token):
        user.is_email_verified = True
        user.save()
        return redirect('app:home')

    return redirect('accounts:verify')

@login_required(login_url='accounts:login', redirect_field_name='')
def signout(request):
    logout(request)
    return redirect('accounts:login')

@login_required(login_url='accounts:login', redirect_field_name='')
def resend(request):
    if request.user.is_email_verified:
        return redirect("app:home")

    send_activation_email(request, request.user)
    messages.success(request, 'A new verification link has been sent to the email address you provided during registration.')
    return redirect('accounts:verify')

accounts/templates/accounts/change-password.html
{% extends 'main.html' %}

{% block content %}
<div class="flex items-center justify-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
    <div class="p-8 w-full xs:w-7/8 sm:w-5/6 md:w-2/3 lg:w-1/3 bg-white rounded-lg shadow-xl dark:bg-gray-800">
        <!-- Form Header -->
        <div class="text-center max-w-full">
            <h5 class="text-xl font-medium text-gray-700 dark:text-gray-200">Password change</h5>
            <p class="text-gray-500 dark:text-gray-200 text-xs mt-2">
                Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.
            </p>
        </div>

        <form method="POST" class="mt-6 mb-2">
            {% csrf_token %}

            <div class="form-group">
                <div class="fildWrapper relative f-outline mb-6">
                    <input class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input appearance-none bg-transparent" id="{{ form.old_password.id_for_label }}" name="{{ form.old_password.html_name }}" value="{{ form.old_password.value }}" type="password" placeholder=' ' required />
                    <label for="old_password" class="absolute ml-4 top-0 text-sm text-gray-400 dark:text-gray-300 bg-white ark:bg-gray-800 mt-2 -z-1 duration-300 origin-0">Old password</label>
                </div>
                {% if form.old_password.errors %}
                    {% for error in form.old_password.errors  %}
                        <p class="text-xs text-red-400 mt-1 ml-1">* {{ error|escape }}</p>
                    {% endfor %}
                {% endif %}

                <hr>

                <div class="fildWrapper relative f-outline mt-6">
                    <input class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input appearance-none bg-transparent" id="{{ form.new_password1.id_for_label }}" name="{{ form.new_password1.html_name }}" value="{{ form.new_password1.value }}" type="password" placeholder=' ' required />
                    <label for="new_password1" class="absolute ml-4 top-0 text-sm text-gray-400 dark:text-gray-300 bg-white ark:bg-gray-800 mt-2 -z-1 duration-300 origin-0">New password</label>
                </div>

                <div class="fildWrapper relative f-outline mt-6">
                    <input class="block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input appearance-none bg-transparent" id="{{ form.new_password2.id_for_label }}" name="{{ form.new_password2.html_name }}" value="{{ form.new_password2.value }}" type="password" placeholder=' ' required />
                    <label for="new_password2" class="absolute ml-4 top-0 text-sm text-gray-400 dark:text-gray-300 bg-white ark:bg-gray-800 mt-2 -z-1 duration-300 origin-0">Confirm new password</label>
                </div>

                {% if form.new_password2.errors %}
                    {% for error in form.new_password2.errors  %}
                        <p class="text-xs text-red-400 mt-1 ml-1">* {{ error|escape }}</p>
                    {% endfor %}
                {% endif %}

                <!-- Submit Button -->
                <button class="block w-full px-4 py-2 mt-5 text-sm font-medium leading-5 text-center text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" type="submit">Change my password</button>
            </div>
        </form>
    </div>
</div>
<style>
    .f-outline input:focus-within ~ label,
    .f-outline input:not(:placeholder-shown) ~ label {
        margin-top: 14px;
        transform: translateY(-1.5rem) translatex(-1rem) scaleX(0.80) scaleY(0.80);
    }
</style>
{% endblock %}

accounts/templates/accounts/password-change-done.html
{% extends 'main.html' %}

{% block content %}
<div class="flex items-center justify-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
    <div class="p-8 w-full xs:w-7/8 sm:w-5/6 md:w-2/3 lg:w-1/3 bg-white rounded-lg shadow-xl dark:bg-gray-800">

        <div class="text-center max-w-full mb-4">
            <h5 class="text-xl font-medium text-gray-700 dark:text-gray-200">Password change successful</h5>
            <small class="text-gray-500 dark:text-gray-200">
                Your password was changed.
            </small>
        </div>

        <div>
            <form method="" action="{% url 'app:home' %}" class="mb-2">
                {% csrf_token %}
                <button class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5 text-center text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" type="submit">Return home</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/password-reset-done.html
{% extends 'main.html' %}

{% block content %}
<div class="flex items-center justify-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
    <div class="p-8 w-full xs:w-7/8 sm:w-5/6 md:w-2/3 lg:w-1/3 bg-white rounded-lg shadow-xl dark:bg-gray-800">

        <div class="text-center max-w-full mb-4">
            <h5 class="text-xl font-medium text-gray-700 dark:text-gray-200">Password reset link sent</h5>
        </div>
        
        <div class="mb-4 text-sm text-gray-500 dark:text-gray-200">
            <p class="mb-2">
                We've emailed you instruction for setting your password, if an account exists with the email you entered. You should receive them shortly.
            </p>

            <p>
                If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
            </p>
        </div>

        <div>
            <form method="" action="{% url 'accounts:password_reset' %}" class="mb-2">
                {% csrf_token %}
                <button class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5 text-center text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" type="submit">Go back</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/password-reset-html-email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Reset Password</title>
    <meta name="viewport" content="width = 375, initial-scale = -1">
  </head>

  <body style="background-color: #ffffff; font-size: 16px;">
    <center>
      <table align="center" border="0" cellpadding="0" cellspacing="0" style="height:100%; width:600px;">
          <!-- BEGIN EMAIL -->
          <tr>
            <td align="center" bgcolor="#ffffff" style="padding:30px">
               <p style="text-align:left">
                    Hello {{ user.get_username }},<br><br>You're receiving this email because you have requested a password reset for your user account at {{ site_name }}. Please click the button below to go to the following page and choose a new password:
                </p>

                <p>
                    <a target="_blank" style="text-decoration:none; background-color: black; border: black 1px solid; color: #fff; padding:10px 10px; display:block;" href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">
                        <strong>Reset Password</strong>
                    </a>
                </p>

                <p style="text-align:left">
                    This link can only be used once. If you need to reset your password again, please visit <a href="{{ protocol }}://{{domain}}">{{ site_name }}</a> and request another reset.<br><br>If you did not make this request, you can simply ignore this email. Thanks for using our site!
                </p>

                <p style="text-align:left">
                    Sincerely,<br>The {{ site_name }} Team
                </p>

                <hr>

                <p style="text-align:left">
                    If you are having trouble clicking the "Reset Password" button, copy and past the URL below to your web browser: 
                    {% block reset_link %}
                        {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
                    {% endblock %}
                </p>
            </td>
          </tr>
        </tbody>
      </table>
    </center>
  </body>
</html>

accounts/templates/accounts/signin.html
{% extends 'main.html' %}

{% block content %}
{% load socialaccount %}
{% load static %}
<div class="flex items-center justify-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">

    <!-- Box Shadow -->
    <div class="p-6 sm:p-12 w-full xs:w-7/8 sm:w-5/6 md:w-2/3 lg:w-1/3 bg-white rounded-lg shadow-xl dark:bg-gray-800">

        <div class="w-full">

            <!-- Form Header -->
            <div class="flex justify-between text-left">
                <div class="max-w-full">
                    <h1 class="mb-4 text-xl font-semibold text-gray-700 dark:text-gray-200">Log in</h1>
                </div>
                <div class="max-w-full">
                    <p class="text-gray-400 text-sm">
                        or 
                        <a class="text-sm font-light text-purple-600 dark:text-purple-400 hover:underline"
                        href="{% url 'accounts:register' %}">Create an account</a>
                    </p>
                </div>
            </div>

            <!-- Registration Form -->
            <form method="POST">
                {% csrf_token %}

                <!-- Email Address -->
                <div class="fildWrapper relative f-outline">
                    {{ form.username }}
                    <label for="username" class="absolute ml-4 top-0 text-sm text-gray-400 dark:text-gray-300 bg-white ark:bg-gray-800 mt-2 -z-1 duration-300 origin-0">Username</label>
                </div>

                <!-- Password -->
                <div class="fildWrapper relative f-outline mt-5">
                    {{ form.password }}
                    <label for="password" class="absolute ml-4 top-0 text-sm text-gray-400 dark:text-gray-300 bg-white ark:bg-gray-800 mt-2 -z-1 duration-300 origin-0">Password</label>
                </div>

                {% for message in messages %}
                    <p class="text-xs text-red-400 mt-1 ml-1">* {{ message }}</p>
                {% endfor %}

                <!-- Remember Me -->
                <div class="flex justify-between text-left mt-6">
                    <div class="text-sm max-w-full fieldWrapper">
                        <label class="flex items-center dark:text-gray-400">
                            <input type="checkbox" value='lsRememberMe' id="rememberMe" class="text-purple-600 form-checkbox focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray">
                            <span class="ml-2">
                                Remember me
                            </span>
                        </label>
                    </div>
                    <div class="text-sm max-w-full fieldWrapper">
                        <a class="text-sm font-light text-purple-600 dark:text-purple-400 hover:underline"
                        href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
                    </div>
                </div>

                <!-- Submit Button -->
                <button class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5 text-center text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" onclick="lsRememberMe()" type="submit">Log in</button>
            </form>

            <div class="w-full relative mt-8">
                <hr class="text-gray-300">
                <div class="absolute inset-center bg-white text-gray-400 top-0 px-4 text-sm">or log in with</div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 md:gap-4 mt-8">

                <form action="{% provider_login_url 'google' %}">
                    {% csrf_token %}

                    <button class="flex items-center justify-center w-full px-4 py-2 text-sm font-medium leading-5 text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
                        <img class="w-5 h-5 mr-2" src="https://img.icons8.com/ios/50/000000/google-plus.png"/>
                        Google
                    </button>
                </form>

                <form class="mt-4 md:mt-0" action="{% provider_login_url 'github' %}">
                    {% csrf_token %}

                    <button class="flex items-center justify-center w-full px-4 py-2 text-sm font-medium leading-5 text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray">
                        <svg
                        class="w-4 h-4 mr-2"
                        aria-hidden="true"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        >
                        <path
                            d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"
                        />
                        </svg>
                        Github
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
    .f-outline input:focus-within ~ label,
    .f-outline input:not(:placeholder-shown) ~ label {
        margin-top: 14px;
        transform: translateY(-1.5rem) translatex(-1rem) scaleX(0.80) scaleY(0.80);
    }
    .inset-center {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
</style>

<script>
    const rmCheck = document.getElementById("rememberMe"),
    usernameInput = document.getElementById("username"),
    passwordInput = document.getElementById("password");

    if (localStorage.checkbox && localStorage.checkbox !== "") {
        rmCheck.setAttribute("checked", "checked");
        usernameInput.value = localStorage.username;
        passwordInput.value = localStorage.password;
    } else {
        rmCheck.removeAttribute("checked");
        usernameInput.value = "";
        passwordInput.value = "";
    }

    function lsRememberMe() {
        if (rmCheck.checked && usernameInput.value !== "") {
            localStorage.username = usernameInput.value;
            localStorage.password = passwordInput.value;
            localStorage.checkbox = rmCheck.value;
        } else {
            localStorage.username = "";
            localStorage.password = "";
            localStorage.checkbox = "";
        }
    }
</script>
{% endblock content %}

accounts/templates/accounts/verification-mail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <title>Verfy Email Address</title>
    <meta name="viewport" content="width = 375, initial-scale = -1">
  </head>

  <body style="background-color: #ffffff; font-size: 16px;">
    <center>
      <table align="center" border="0" cellpadding="0" cellspacing="0" style="height:100%; width:600px;">
          <!-- BEGIN EMAIL -->
          <tr>
            <td align="center" bgcolor="#ffffff" style="padding:30px">
               <p style="text-align:left">
                    Hello {{ user.username }},<br><br>You're receiving this email because you have requested to create an user account at {{ domain }}. Please click the button below to verify your email address:
                </p>

                <p>
                    <a target="_blank" style="text-decoration:none; background-color: black; border: black 1px solid; color: #fff; padding:10px 10px; display:block;" href="{{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}">
                        <strong>Verfy Email Address</strong>
                    </a>
                </p>

                <p style="text-align:left">
                    This link can only be used once. If you did not make this request, you can simply ignore this email. Thanks for using our site!
                </p>

                <p style="text-align:left">
                    Sincerely,<br>The {{ domain }} Team
                </p>

                <hr>

                <p style="text-align:left">
                    If you are having trouble clicking the "Verfy Email Address" button, copy and past the URL below to your web browser: 
                    {% block reset_link %}
                        {{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
                    {% endblock %}
                </p>
            </td>
          </tr>
        </tbody>
      </table>
    </center>
  </body>
</html>

accounts/templates/accounts/verify-email.html
{% extends 'main.html' %}

{% block content %}
<div class="flex items-center justify-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
    <div class="p-8 w-full xs:w-7/8 sm:w-5/6 md:w-2/3 lg:w-1/3 bg-white rounded-lg shadow-xl dark:bg-gray-800">
        
        {% url 'accounts:register' as register_url %}
        {% if register_url in request.META.HTTP_REFERER %}
            <div class="mb-4 text-sm text-gray-600">
                Thanks for signing up! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn't receive the email, we will gladly send you another.
            </div>
        {% else %}
            <div class="mb-4 text-sm text-gray-600">
                Welcome back! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn't receive the email, we will gladly send you another.
            </div>
        {% endif %}

        {% url 'accounts:verify' as verify_url %}
        {% if verify_url in request.META.HTTP_REFERER %}
            {% for message in messages %}
                <div class="mb-4 font-medium text-sm text-green-600">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        

        <div class="mt-4 flex items-center justify-between">
            <form method="POST" action="{% url 'accounts:resend' %}">
                {% csrf_token %}
                <div>
                    <button class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5 text-center text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" type="submit">Resend Verification Email</button>
                </div>
            </form>

            <form method="POST" action="{% url 'accounts:logout' %}">
                {% csrf_token %}

                <button type="submit" class="underline text-sm text-gray-600 hover:text-gray-900">
                    Logout
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}